### PR TITLE
Fix/version compare test

### LINKED ISSUE #19: Fix version check in tests
The current approach is bad, for example `1.10.1` > `1.9.9` but our test fails, since we are doing string matching

https://github.com/safedep/dry/actions/runs/14640940124/job/41082948667#step:8:367

### PR DESCRIPTION
**Pull request by KunalSin9h**
fixes #19 

This PR introduces a more sophisticated solution for comparing version. 
Handles Semantic versioning with `v` prefix and git hub branch reference.

### CODE REVIEW

File: utils/version.go [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+
+import (
+	"strconv"
+	"strings"
+)
+
+type Version string
+
+// IsGreaterThenOrEqualTo compares its version to be greater than the provided input
+func (v Version) IsGreaterThenOrEqualTo(version string) bool {
```
Comment (abhisek) [inline utils/version.go:11]: Can you use this instead of custom logic?

https://github.com/safedep/dry/tree/main/semver

Comment (KunalSin9h) [reply utils/version.go]: done

**Review by abhisek — APPROVED** [review]
